version: "3.7"

services:
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    networks:
      - accounting-net
  backend:
    build:
      context: .
      dockerfile: ./docker/Backend.Dockerfile
    ports:
      - 8080:8080
    networks:
      - accounting-net

networks:
  accounting-net:
