// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"database/sql"
	"time"
)

type Expense struct {
	ID          int64
	Price       sql.NullFloat64
	Expensedate time.Time
}

type Income struct {
	ID         int64
	Price      sql.NullFloat64
	Incomedate time.Time
}

type Payment struct {
	ID        int64
	Expenseid int64
	Price     float64
	Paiddate  time.Time
}
