// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"database/sql"
)

type Expense struct {
	ID          int64
	Price       sql.NullFloat64
	Expensedate sql.NullTime
}

type Income struct {
	ID         int64
	Price      sql.NullFloat64
	Incomedate sql.NullTime
}

type Payment struct {
	ID        int64
	Expenseid int64
	Price     float64
	Paiddate  sql.NullTime
}
