// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql_types

import (
	"sapp/paperless-accounting/paperless"
)

type NewPayment struct {
	Date      paperless.PaperlessTime `json:"date"`
	Value     float64                 `json:"value"`
	ExpenseID string                  `json:"expenseId"`
}

type UpdateExpense struct {
	Date        *paperless.PaperlessTime `json:"date,omitempty"`
	Value       *float64                 `json:"value,omitempty"`
	PaperlessID string                   `json:"paperlessID"`
}

type UpdateIncome struct {
	Date        *paperless.PaperlessTime `json:"date,omitempty"`
	Value       *float64                 `json:"value,omitempty"`
	PaperlessID string                   `json:"paperlessID"`
}

type UpdatePayment struct {
	ID        string                   `json:"id"`
	Date      *paperless.PaperlessTime `json:"date,omitempty"`
	Value     *float64                 `json:"value,omitempty"`
	ExpenseID *string                  `json:"expenseId,omitempty"`
}
