// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql_types

import (
	"sapp/paperless-accounting/paperless"
)

type ChartEntry struct {
	Date     paperless.PaperlessTime `json:"date"`
	Category string                  `json:"category"`
	Value    float64                 `json:"value"`
}

type NewPayment struct {
	Date      paperless.PaperlessTime `json:"date"`
	Value     float64                 `json:"value"`
	ExpenseID int                     `json:"expenseId"`
}

type UpdateExpense struct {
	Date        *paperless.PaperlessTime `json:"date,omitempty"`
	Value       *float64                 `json:"value,omitempty"`
	PaperlessID int                      `json:"paperlessID"`
}

type UpdateIncome struct {
	Date        *paperless.PaperlessTime `json:"date,omitempty"`
	Value       *float64                 `json:"value,omitempty"`
	PaperlessID int                      `json:"paperlessID"`
}

type UpdatePayment struct {
	ID        int                      `json:"id"`
	Date      *paperless.PaperlessTime `json:"date,omitempty"`
	Value     *float64                 `json:"value,omitempty"`
	ExpenseID *int                     `json:"expenseId,omitempty"`
}
