# Generated by Django 4.2.3 on 2023-07-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid', models.BooleanField()),
                ('paidDate', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
