# Generated by Django 4.2.3 on 2023-07-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_tag', models.CharField(max_length=32)),
                ('income_tag', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaperlessDocument',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
